### ISSUE TITLE
Codeunit 82111 - WaldoNAVPad Text Parse Meth / Function: AddToBuffer

### ISSUE THREAD

**Issue by Maaaxime** [waldo1001/Waldo.NAV#1]
Hello Waldo,

I tweaked you NavPad to use it in the Sales Lines directly without blob field. 
I think I found a little mistake, where NAV don't understand you ;)

In the function "AddToBuffer", you insert some information in the Buffer but NAV don't understand which "separator" to use (the parameters or the field).

So replace this
![original](https://cloud.githubusercontent.com/assets/18112977/14579831/cd488e6c-03b8-11e6-8e6d-c201e8cb458c.png)

By this : 
![modified](https://cloud.githubusercontent.com/assets/18112977/14579834/eb58e726-03b8-11e6-832b-894e9ecdbdfc.png)

Really nice job! :+1: 
Have a nice day.

PS : Maybe a little bit too much Codeunit to Sell to the Customer just for a Notepad! So i made a concatenation in one unique :8ball:

**Comment by waldo1001** [comment]
Oops .. good catch!  thanks, this is a stupid mistake :-/. (but then again .. there are no "smart mistakes", are there ;-).
