### ISSUE TITLE
Tiny MCE v4 shutdown

### ISSUE THREAD

**Issue by xperia-droid** [waldo1001/Waldo.NAV#4]
Hi Waldo,

We have been using your Waldo NAV Pad in our Dynamics NAV system for a few years now. But we got a message that the v4 version is only supported until Feb 25, 2021:
![image](https://user-images.githubusercontent.com/24463981/106741987-b7945080-661c-11eb-9e87-418396961edb.png)
 
To accommodate those, we first tried to include the v5 of Tiny Editor ourselves. 
So we tried to change the URL in manifest.xml to use the v5 of tiny mce, but in the end the page only shows white.
![image](https://user-images.githubusercontent.com/24463981/106743368-96ccfa80-661e-11eb-8aec-4d659b518351.png)
![image](https://user-images.githubusercontent.com/24463981/106743567-de538680-661e-11eb-9001-3d9a24587ff1.png)

Then we tried to download the v4 of tiny mce as a workaround and put it in the script folder of ressources.zip and paste it in manifest.xml. But again it only shows white :(.
![image](https://user-images.githubusercontent.com/24463981/106744063-85382280-661f-11eb-80be-0f519b2016d7.png)

We updated the ressources.zip in the following way:
- Change manifest.xml
- Pasted into the ressources.zip
- On the second try, we added the tinymce.min.js to the script folder as well
- In the NAV Control Add-In page we updated the resource for the Waldo.NAV.TinyMCEControl add-in
- We have compiled all 17 WaldoNAVPad objects
- Restart RTC and open page 82101

We tried to integrate the other tiny MCE editor: https://github.com/navaddins/TinyMCEEditor-CAL

But in our NAV system it only shows an endless loading screen. We were able to use it in a completely offline vm without any problems, but in our Dynamics NAV system it only shows an endless loading screen.
![image](https://user-images.githubusercontent.com/24463981/106743143-46559d00-661e-11eb-8a5c-1ec921098efb.png)

We have not found another TinyMCE editor / RTF editor that works with NAV and has the features we use on a daily basis. 

So our last hope is on you to please update your control add-in to work on v5. On our end, we can only fall back on the NAV standard text editor.

Thank you very much for reading and your help :).

With kind regards,
Daniel

**Comment by xperia-droid** [comment]
Some Dynamics NAV System information:
- We are using NAV BC 14 CU 10 in DE Version
- Primary using the RTC-Client of the NAV System.
- We haven't tried integrating the AL version of NAV PAD yet, as we have some old customers using NAV 2015 who have the same issue, that it will work only until 25. Feb.

**Comment by waldo1001** [comment]
Sorry to hear about this.  I have no problem trying to look at this .. but it's been soooo long that I've done anything C/AL (let alone control addin) .. .  And the time doesn't permit me to invest in this any time soon .. .

If it has worked on another system, can it be related to internet/proxy settings, since the scripts needs to be downloaded?

**Comment by xperia-droid** [comment]
Thank you very much for your answer. 

Something like, "And the time doesn't permit me to invest in this any time soon ..." is what I was thinking before.

Regarding your question, I can say that it has nothing to do with the proxy settings. Because we use the default network settings from Internet Explorer:
![image](https://user-images.githubusercontent.com/24463981/106892664-a9ae0080-66ec-11eb-9396-e7712adb69b7.png)


We think that the problem occurs only in the RTC.

Because on the web client we can use the other TinyMCE editor without any problems, but in the RTC we get the endless loading screen.
![image](https://user-images.githubusercontent.com/24463981/106887864-107beb80-66e6-11eb-9394-8d85529e5fed.png)

With your extension it behaves in the WebClient as follows:
![image](https://user-images.githubusercontent.com/24463981/106891517-158f6980-66eb-11eb-8f14-2a7961abeb4e.png)
![image](https://user-images.githubusercontent.com/24463981/106891554-217b2b80-66eb-11eb-82f7-c11398716628.png)

And with the attached snippet from Tiny.cloud I can test on the problematic server that it works at least basically:
![image](https://user-images.githubusercontent.com/24463981/106887149-0c9b9980-66e5-11eb-9c72-ffbe4cd25a8b.png)

I had to add the "mark of the web" line  to the html file. 
With the "mark of the web" feature, the editor opens immediately.
Otherwise I get an error message from Internet Explorer that I am using unsigned javascript and I have to allow it:
![image](https://user-images.githubusercontent.com/24463981/106892014-c5fd6d80-66eb-11eb-8633-3f02f245bcc9.png)

The message regarding blocked Active-X scripts in Internet Explorer does not change when I use http or https to access the .js file inside the html-file.

I don't know if there is a way to add the "mark of the web" feature to the Dynamics NAV javascript. Or if this is the real problem.

AFAIK Dynamics NAV uses the Internet Explorer engine to render the javascript. So we have already tried changing the Internet Explorer website settings to allow all scripts etc, but nothing has changed. Your addin in v5 or the other addin is just not rendering in the Dynamics NAV RTC.

Thanks for reading :).

**Comment by fve1611** [comment]
Hi,
Any updates on this topic?
I am also seeking a solution for this, but so far without success...

**Comment by waldo1001** [comment]
Not from my side, I'm afraid.  As I said, I'm not going to be able to put any time in this any time soon .. especially not on C/AL versions .. which is completely off my radar .. :(.  I hope there will be someone from the community providing a solution 🙏

**Comment by waldo1001** [comment]
I just read this : https://twitter.com/joinTiny/status/1359960384728231936?s=20

may be it can help ...

**Comment by navaddins** [comment]
@fve1611 
> Hi,
> Any updates on this topic?
> I am also seeking a solution for this, but so far without success...

Hello pls try to use https://github.com/navaddins/TinyMCEEditor-CAL

@NAV-Management  reported issue is not related with TimyMCE Editor. Anyway it's solved

**Comment by navaddins** [comment]
@waldo1001 
> Not from my side, I'm afraid. As I said, I'm not going to be able to put any time in this any time soon .. especially not on C/AL versions .. which is completely off my radar .. :(. I hope there will be someone from the community providing a solution 🙏

I developed TinyMCEEditor what you do for us. It's working 2016 to BC and online and offline mode. Hope this help to others

[TinyMCEEditor-CAL](https://github.com/navaddins/TinyMCEEditor-CAL)
[TinyMCEEditor-AL](https://github.com/navaddins/TinyMCEEditor-AL)
Please accept my apologize, if I'm look like adv my product in your comments. I just want to share only

Regards,

**Comment by waldo1001** [comment]
@navaddins , thanks a lot!  This will sure help other people that use it!!
